# Carga de datos

Este notebook carga el dataset de solicitudes de crédito (`Base_de_datos.csv`) 
para su uso en las siguientes etapas del pipeline (EDA, feature engineering, entrenamiento).

In [1]:
import pandas as pd
df = pd.read_csv('../../Base_de_datos.csv')
df.head()

                                                   tipo_credito;fecha_prestamo;capital_prestado;plazo_meses;edad_cliente;tipo_laboral;salario_cliente;total_otros_prestamos;cuota_pactada;puntaje;puntaje_datacredito;cant_creditosvigentes;huella_consulta;saldo_mora;saldo_total;saldo_principal;saldo_mora_codeudor;creditos_sectorFinanciero;creditos_sectorCooperativo;creditos_sectorReal;promedio_ingresos_datacredito;tendencia_ingresos;Pago_atiempo
7;21/12/2024 11:31;3692160;10;42;Independiente;...  768094;695.0;10;5;0.0;51258.0;51258.0;0.0;5;0;...
4;22/4/2025 09:47;840000;6;60;Empleado;3000000;...  227787;789.0;3;1;0.0;8673.0;8673.0;0.0;0;0;2;9...
9;8/1/2026 12:22;5974028;10;36;Independiente;40...  613894;740.0;4;5;0.0;18702.0;18702.0;0.0;3;0;0...
4;4/8/2025 12:04;1671240;6;48;Empleado;1524547;...  227787;837.0;4;4;0.0;15782.0;15782.0;0.0;3;0;0...
9;26/4/2025 11:24;2781636;11;44;Empleado;500000...  227787;771.0;4;6;0.0;204804.0;204804.0;0.0;3;0...

In [2]:
import pandas as pd
df = pd.read_csv('../../Base_de_datos.csv', sep=';')
df.head()

,tipo_credito,fecha_prestamo,capital_prestado,plazo_meses,edad_cliente,tipo_laboral,salario_cliente,total_otros_prestamos,cuota_pactada,puntaje,...,saldo_mora,saldo_total,saldo_principal,saldo_mora_codeudor,creditos_sectorFinanciero,creditos_sectorCooperativo,creditos_sectorReal,promedio_ingresos_datacredito,tendencia_ingresos,Pago_atiempo
0,7,21/12/2024 11:31,3692160,10,42,Independiente,8000000,2500000,341296,"88,768094",...,0.0,51258.0,51258.0,0.0,5,0,0,908526.0,Estable,1
1,4,22/4/2025 09:47,840000,6,60,Empleado,3000000,2000000,124876,"95,227787",...,0.0,8673.0,8673.0,0.0,0,0,2,939017.0,Creciente,1
2,9,8/1/2026 12:22,5974028,10,36,Independiente,4036000,829000,529554,"47,613894",...,0.0,18702.0,18702.0,0.0,3,0,0,NaN,NaN,0
3,4,4/8/2025 12:04,1671240,6,48,Empleado,1524547,498000,252420,"95,227787",...,0.0,15782.0,15782.0,0.0,3,0,0,1536193.0,Creciente,1
4,9,26/4/2025 11:24,2781636,11,44,Empleado,5000000,4000000,217037,"95,227787",...,0.0,204804.0,204804.0,0.0,3,0,1,933473.0,Creciente,1

In [3]:
print(df.shape)
df.info()

(10763, 23)
<class 'pandas.DataFrame'>
RangeIndex: 10763 entries, 0 to 10762
Data columns (total 23 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   tipo_credito                   10763 non-null  int64
 1   fecha_prestamo                 10763 non-null  str
 2   capital_prestado               10763 non-null  int64
 3   plazo_meses                    10763 non-null  int64
 4   edad_cliente                   10763 non-null  int64
 5   tipo_laboral                   10763 non-null  str
 6   salario_cliente                10763 non-null  int64
 7   total_otros_prestamos          10763 non-null  int64
 8   cuota_pactada                  10763 non-null  int64
 9   puntaje                        10763 non-null  str
 10  puntaje_datacredito            10757 non-null  float64
 11  cant_creditosvigentes          10763 non-null  int64
 12  huella_consulta                10763 non-null  int64
 13  saldo_mora                     10607 non-null  float64
 14  saldo_total                    10607 non-null  float64
 15  saldo_principal                10358 non-null  float64
 16  saldo_mora_codeudor            10173 non-null  float64
 17  creditos_sectorFinanciero      10763 non-null  int64
 18  creditos_sectorCooperativo     10763 non-null  int64
 19  creditos_sectorReal            10763 non-null  int64
 20  promedio_ingresos_datacredito  7833 non-null   float64
 21  tendencia_ingresos             7831 non-null   str
 22  Pago_atiempo                   10763 non-null  int64
dtypes: float64(6), int64(13), str(4)
memory usage: 2.3 MB